## Project data scince 
students:

1- Sara Alharbi 
2- Abeer Aljabri
3- Noura Alangri

In [54]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import confusion_matrix
import numpy as np

In [55]:
# Read your CSV file
data = pd.read_csv('dataset2.csv')

In [56]:
# Preprocess the data: convert categorical variables to numerical using one-hot encoding
data = pd.get_dummies(data, columns=['Display Resolution', 'color', 'Operating System'])


In [57]:
# Split the dataset into features (X) and the target variable (y)
X = data.drop(['Brand' , 'Name'], axis=1)
y = data['Brand']


In [58]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [59]:
# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the classifiers
classifiers = {
    'Logistic Regression': LogisticRegression(),
    'SVM': SVC(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier()
}


In [61]:
# Train and evaluate the classifiers
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    report= classification_report(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} accuracy: {accuracy:.2f}")
    print(report)

Logistic Regression accuracy: 0.85
              precision    recall  f1-score   support

         BBK       1.00      0.50      0.67         4
      Huawei       0.86      1.00      0.92         6
      Lenovo       1.00      1.00      1.00         2
    Motorola       0.33      1.00      0.50         1
     OnePlus       1.00      1.00      1.00         4
        Oppo       1.00      0.67      0.80         3

    accuracy                           0.85        20
   macro avg       0.87      0.86      0.81        20
weighted avg       0.92      0.85      0.86        20

SVM accuracy: 0.75
              precision    recall  f1-score   support

         BBK       1.00      0.50      0.67         4
      Huawei       0.67      1.00      0.80         6
      Lenovo       0.00      0.00      0.00         2
    Motorola       0.33      1.00      0.50         1
     OnePlus       1.00      1.00      1.00         4
        Oppo       1.00      0.67      0.80         3

    accuracy           

c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

Random Forest accuracy: 0.90
              precision    recall  f1-score   support

         BBK       1.00      1.00      1.00         4
      Huawei       1.00      1.00      1.00         6
      Lenovo       0.00      0.00      0.00         2
    Motorola       0.33      1.00      0.50         1
     OnePlus       1.00      1.00      1.00         4
        Oppo       1.00      1.00      1.00         3

    accuracy                           0.90        20
   macro avg       0.72      0.83      0.75        20
weighted avg       0.87      0.90      0.88        20



c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [62]:
# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[4 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 3]]


In [70]:
# Calculate FP,FN,TP, TN
FP = conf_matrix.sum(axis=0) - np.diag(conf_matrix)
FN = conf_matrix.sum(axis=1) - np.diag(conf_matrix)
TP = np.diag(conf_matrix)
TN = conf_matrix.sum() - (FP + FN + TP)

# Print TP, TN, FP, FN for each class
print("TP: ", TP)
print("TN: ", TN)
print("FP: ", FP)
print("FN: ", FN)

# Print the total TP, TN, FP, FN 
total_TP = sum(TP)
total_TN = sum(TN)
total_FP = sum(FP)
total_FN = sum(FN)

print("TP: ", total_TP)
print("TN: ", total_TN)
print("FP: ", total_FP)
print("FN: ", total_FN)


TP:  [4 6 0 1 4 3]
TN:  [16 14 18 17 16 17]
FP:  [0 0 0 2 0 0]
FN:  [0 0 2 0 0 0]
TP:  18
TN:  98
FP:  2
FN:  2
